CREATE TABLE RuoliUtenti
(
	RuoloId INT NOT NULL,
	UtenteId NVARCHAR(50) NOT NULL,
	DataInserimento DATE DEFAULT(GETDATE()),
	CONSTRAINT PK_RuoliUtenti PRIMARY KEY (RuoloId,UtenteId),
	CONSTRAINT FK_RuoliUtentiUtenti FOREIGN KEY (UtenteId) REFERENCES Utenti(UserName)
		ON UPDATE CASCADE
		ON DELETE CASCADE,
	CONSTRAINT FK_RuoliUtentiRuoli FOREIGN KEY (RuoloId) REFERENCES Ruoli(RuoloId)
		ON UPDATE CASCADE
		ON DELETE CASCADE
)
